### ISSUE TITLE
Lock issue

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-job-queue#24]
I've got a job that runs every hour, but when I checked on it this morning, it never finished and it's stuck locked.

![screen shot 2015-06-18 at 10 00 57 am](https://cloud.githubusercontent.com/assets/27936/8236960/f0d26d0a-15a0-11e5-853a-bfc7ab323239.png)

![screen shot 2015-06-18 at 10 01 39 am](https://cloud.githubusercontent.com/assets/27936/8236978/0aa45e5a-15a1-11e5-9b65-0c834c73c7d7.png)

Whats the best way for me to debug this?

**Comment by dawnerd** [comment]
https://github.com/firstandthird/hapi-job-queue/blob/master/lib/index.js#L330-L345

Sounds like the callback wasn't called or the task failed. I would put some logging in there and see if the callback is even firing.

**Comment by jgallen23** [comment]
was a user error. closing
